import type { Metadata } from "next"
import {  Poppins } from "next/font/google"
import "./globals.css"
import Navigation from "@/components/layout/Navigation"
import Background from "@/components/layout/Background"

const roboto = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata: Metadata = {
  title: "Neetigya Chahar",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Background />
        <Navigation />
        {children}
      </body>
    </html>
  )
}
